layout_spectrum: 0.4510961
typography_spectrum: 0.6299834
color:
  lightness: 0.682968
  brandStrength: 0.006177349
  saturation: 0.6340641
  rhythmicContrast: 0.6053963
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Undiscovered Italy
